version: '3.9' # ? 

services:
  postgres:
    container_name: pg_db
    image: postgres:15 # postgres:15.7-alpine
    environment: # = / : ??
      POSTGRES_DB: mydb
      POSTGRES_PASSWORD: root
      POSTGRES_USER: admin
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
      - "5050:80"
